/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package focusersimulator;

import ardufocuser.starfocusing.FitsImage;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author josemlp
 */
public class FocuserViwer extends javax.swing.JFrame {

    FocuserSimulator focuser;

   /**
     * Creates new form FocuserViwer
     */
    private BufferedImage img;

    public FocuserViwer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        open_button = new javax.swing.JButton();
        previous_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        focus_progess = new javax.swing.JProgressBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        text_focus = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        next_button1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lienzo = new focusersimulator.FocuserViwerLienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);

        open_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assert/glyphicons/png/glyphicons-145-folder-open.png"))); // NOI18N
        open_button.setFocusable(false);
        open_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        open_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(open_button);

        previous_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assert/glyphicons/png/glyphicons-171-step-backward.png"))); // NOI18N
        previous_button.setFocusable(false);
        previous_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previous_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previous_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(previous_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assert/glyphicons/png/glyphicons-179-step-forward.png"))); // NOI18N
        next_button.setFocusable(false);
        next_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(next_button);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(focus_progess);
        jToolBar1.add(jSeparator3);

        text_focus.setEditable(false);
        text_focus.setText("0");
        text_focus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_focusActionPerformed(evt);
            }
        });
        jToolBar1.add(text_focus);
        jToolBar1.add(jSeparator2);

        next_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assert/glyphicons/png/glyphicons-194-circle-ok.png"))); // NOI18N
        next_button1.setFocusable(false);
        next_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        next_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_button1ActionPerformed(evt);
            }
        });
        jToolBar1.add(next_button1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(lienzo);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previous_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous_buttonActionPerformed
        focuser.go_to_previous_focus_point();
        FitsImage image = focuser.get_fits_image();
        this.img = image.asBufferedImage();
        lienzo.set_image(this.img);
        text_focus.setText("" + focuser.get_current_focus_value());
        focus_progess.setValue(focuser.get_current_index());
        repaint();
        pack();

// TODO add your handling code here:
    }//GEN-LAST:event_previous_buttonActionPerformed

    private void open_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_buttonActionPerformed

        
        File directorio;
        JFileChooser fc = new JFileChooser();
        int respuesta = fc.showOpenDialog(this);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            directorio = fc.getCurrentDirectory();
            //focuser = new FocuserSimulator("" + directorio);
            focuser = new FocuserSimulator("../images/nucleo");
            FitsImage image = focuser.get_fits_image();
            this.img = image.asBufferedImage();
            lienzo.set_image(this.img);
            focus_progess.setMaximum(focuser.get_size() - 1);
            focus_progess.setValue(focuser.get_current_index());
            text_focus.setText("" + focuser.get_current_focus_value());
            repaint();
            pack();

        }

// TODO add your handling code here:
    }//GEN-LAST:event_open_buttonActionPerformed

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed

        focuser.go_to_next_focus_point();
        FitsImage image = focuser.get_fits_image();
        this.img = image.asBufferedImage();
        lienzo.set_image(this.img);
        text_focus.setText("" + focuser.get_current_focus_value());
        focus_progess.setValue(focuser.get_current_index());
        repaint();
        pack();

// TODO add your handling code here:
    }//GEN-LAST:event_next_buttonActionPerformed

    private void text_focusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_focusActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_text_focusActionPerformed

    private void next_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_button1ActionPerformed
    focuser.autofocus() ;      
           
    }//GEN-LAST:event_next_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FocuserViwer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FocuserViwer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FocuserViwer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FocuserViwer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FocuserViwer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar focus_progess;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private focusersimulator.FocuserViwerLienzo lienzo;
    private javax.swing.JButton next_button;
    private javax.swing.JButton next_button1;
    private javax.swing.JButton open_button;
    private javax.swing.JButton previous_button;
    private javax.swing.JTextField text_focus;
    // End of variables declaration//GEN-END:variables
}
